---
- service: name=rabbitmq-server state=started
  sudo: true
- rabbitmq_user: user={{ rmqUser }}
                 password={{ rmqPass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  sudo: true
- shell: pkill -f "celery worker"
  sudo: true
  ignore_errors: yes
- shell: celery -A jobQueue worker --loglevel=info --logfile=/tmp/job-queue.log --concurrency=10 --detach
  environment:
    PYTHONPATH: "/data-act/core"
  args:
    chdir: /data-act/core/dataactcore/utils/
