---
- shell: /opt/logstash/bin/logstash -f /data-act/data-act-logging.conf &
- name: stop filebeat
  shell: systemctl stop filebeat
  sudo: true
  ignore_errors: yes
- name: start filebeat
  shell: systemctl start filebeat
  sudo: true
- service: name=rabbitmq-server state=started
  sudo: true
- rabbitmq_user: user={{ rmqUser }}
                 password={{ rmqPass }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  sudo: true
- shell: pkill -f "celery worker"
  ignore_errors: yes
- shell: rm celeryd.pid
  ignore_errors: yes
  args:
    chdir: /data-act/backend/dataactcore/utils/
- shell: celery -A jobQueue worker --loglevel=info --logfile=/tmp/job-queue.log --concurrency=10 --detach
  environment:
    PYTHONPATH: "/data-act/backend"
  args:
    chdir: /data-act/backend/dataactcore/utils/