---
- name: core schema update 
  shell: alembic upgrade head
  sudo: true
  environment:
    PYTHONPATH: "data-act/core:/data-act/validator"
  args:
    chdir: /data-act/core/dataactcore
- name: validator schema update 
  shell: alembic upgrade head
  sudo: true
  environment:
    PYTHONPATH: "/data-act/core:/data-act/validator"
  args:
    chdir: /data-act/validator/dataactvalidator/