---
- name: core schema update 
  shell: python3 /data-act/backend/dataactcore/scripts/initialize.py -i
  sudo: true
  environment:
    PYTHONPATH: "/data-act/backend"
    env: "{{ ENV }}"
  args:
    chdir: /data-act/backend/dataactvalidator/scripts/