---
- name: Checkout validator from git
  sudo: true
  git: repo=https://github.com/fedspendingtransparency/data-act-validator.git version={{ VAL_BRANCH }}  dest=/data-act/validator accept_hostkey=true force=yes
- name: Checkout core from git
  sudo: true
  git: repo=https://github.com/fedspendingtransparency/data-act-core.git version={{ CORE_BRANCH }} dest=/data-act/core accept_hostkey=true force=yes
- name: assign ownership of api to ec2-user
  sudo: true
  file: path=/data-act owner=ec2-user recurse=yes