---
- shell: setsebool -P httpd_can_network_connect=1
  sudo: true
- shell: pkill supervisord
  sudo: true
  ignore_errors: yes
- shell: supervisord -c /data-act/web-api/dataactbroker/config/supervisord.conf &
  sudo: true
  environment:
    PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:/data-act/core:/data-act/web-api"
  args:
    chdir: /data-act/web-api/dataactbroker/
